# standard dcgan!
DATA:
  name: "CelebA"
  img_size: 64
  num_classes: 1
MODEL:
  backbone: "resnet"
  jointgan_arch: "concat"
LOSS:
  adv_loss: "hinge"
  jointgan_object: "r"
OPTIMIZATION:
  batch_size: 256
  beta1: 0.0
  beta2: 0.999
  d_updates_per_step: 1