DATA:
  name: "Tiny_ImageNet"
  img_size: 64
  num_classes: 200
MODEL:
  backbone: "resnet"
  jointgan_arch: "concat"
LOSS:
  adv_loss: "wasserstein"
  jointgan_object: "r"
  apply_reg: "l2"
  apply_gp: False
  gp_lambda: 10.0
OPTIMIZATION:
  d_updates_per_step: 2