DATA:
  name: "Tiny_ImageNet"
  img_size: 64
  num_classes: 200
MODEL:
  backbone: "resnet"
  jointgan_arch: "concat"
LOSS:
  adv_loss: "least_square"
  jointgan_object: "r"
OPTIMIZATION:
  d_updates_per_step: 2
