DATA:
  name: "Tiny_ImageNet"
  img_size: 64
  num_classes: 200
MODEL:
  backbone: "resnet"
  jointgan_arch: "ragan"
LOSS:
  adv_loss: "hinge"
  jointgan_object: "r"
  apply_reg: "l2_mean"
OPTIMIZATION:
  d_updates_per_step: 2