DATA:
  name: "Tiny_ImageNet"
  img_size: 64
  num_classes: 200
MODEL:
  backbone: "resnet"
  jointgan_arch: "concat"
LOSS:
  adv_loss: "hinge"
  jointgan_object: "r"
OPTIMIZATION:
  total_steps: 20000