DATA:
  name: "Tiny_ImageNet"
  img_size: 64
  num_classes: 200
MODEL:
  backbone: "resnet"
LOSS:
  adv_loss: "wasserstein"
  apply_gp: True
  apply_reg: "l2_mean"
  gp_lambda: 10.0
OPTIMIZATION:
  beta1: 0.0
  beta2: 0.999