DATA:
  name: "CIFAR10"
  img_size: 32
  num_classes: 10
MODEL:
  backbone: "deep_conv"
  base_dir: "models.jointgan"
  g_conv_dim: "N/A"
  d_conv_dim: "N/A"
LOSS:
  adv_loss: "least_square_relativistic"
  jointgan_gen_pair: "self"
  relativistic: True
OPTIMIZATION:
  d_updates_per_step: 2
  total_steps: 200000
