DATA:
  name: "CIFAR10"
  img_size: 32
  num_classes: 10
MODEL:
  backbone: "deep_conv"
  jointgan_arch: "concat"
  g_conv_dim: "N/A"
  d_conv_dim: "N/A"
LOSS:
  adv_loss: "vanilla"
  relative_sample: "fake"
  add_real : "add_object"
  align_to_real : False
OPTIMIZATION:
  d_updates_per_step: 2
  total_steps: 400000
