DATA:
  name: "CIFAR10"
  img_size: 32
  num_classes: 10
MODEL:
  backbone: "deep_conv"
  jointgan_arch: "rgan"
  rsam_update: "N/A"
  g_conv_dim: "N/A"
  d_conv_dim: "N/A"
LOSS:
  adv_loss: "vanilla"
  relative_sample: "fake"
  align_to_real: True
  add_real : "N/A"
OPTIMIZATION:
  d_updates_per_step: 2
  total_steps: 200000
