DATA:
  name: "CIFAR10"
  img_size: 32
  num_classes: 10
MODEL:
  backbone: "resnet"
  jointgan_arch: "concat"
LOSS:
  adv_loss: "hinge"
  jointgan_object: "r"
  apply_reg: "l2"
OPTIMIZATION:
  d_updates_per_step: 2