DATA:
  name: "CIFAR10"
  img_size: 32
  num_classes: 10
MODEL:
  jointgan_arch: "concat"
LOSS:
  adv_loss: "wasserstein"
  jointgan_object: "f"
  apply_gp: True
  gp_lambda: 10.0
OPTIMIZATION:
  total_steps: 50000