DATA:
  name: "CIFAR10"
  img_size: 32
  num_classes: 10
MODEL:
  backbone: "resnet"
  jointgan_arch: "concat"
LOSS:
  adv_loss: "hinge"
  jointgan_object: "r"
  apply_reg: "N/A"
OPTIMIZATION:
  total_steps: 50000