DATA:
  name: "CIFAR10"
  img_size: 32
  num_classes: 10
MODEL:
  backbone: "deep_conv"
  g_conv_dim: "N/A"
  d_conv_dim: "N/A"
LOSS:
  adv_loss: "least_square"
  apply_reg: "l2_mean"
  lsgan_real_target: 1
  lsgan_fake_target: -1
OPTIMIZATION:
  d_updates_per_step: 2
  total_steps: 200000