DATA:
  name: "CIFAR10"
  img_size: 32
  num_classes: 10
MODEL:
  backbone: "deep_conv"
  base_dir: "models.jointgan"
  
  g_cond_mtd: "cBN"
  d_cond_mtd: "PD"
  apply_d_sn: True
LOSS:
  adv_loss: "hinge_relativistic"
  relativistic: True
OPTIMIZATION:
  d_updates_per_step: 2
  total_steps: 200000
