DATA:
  name: "Tiny_ImageNet"
  img_size: 64
  num_classes: 200
MODEL:
  backbone: "resnet"
  base_dir: "models.jointgan"

LOSS:
  adv_loss: "wasserstein_relativistic"
  apply_gp: True
  gp_lambda: 10.0
  relativistic: True